import type React from "react";
import { Settings, Waves, Wrench, Zap } from "lucide-react";

export type SystemType = "Split" | "Self" | "Splitão";

export interface PhotoTask {
  id: string;
  label: string;
  description: string;
  icon: React.ReactNode;
  preventiveOnly?: boolean;
}

export const PHOTO_TASKS: Record<SystemType, PhotoTask[]> = {
  Split: [
    {
      id: "evap_tec",
      label: "Foto da Etiqueta Técnica da Evaporadora",
      description: "Etiqueta Técnica",
      icon: <Waves className="w-5 h-5" />,
    },
    {
      id: "evap",
      label: "Foto da Evaporadora",
      description: "Evaporadora",
      icon: <Waves className="w-5 h-5" />,
    },
    {
      id: "cond_tec",
      label: "Foto da Etiqueta Técnica da Condensadora",
      description: "Etiqueta Técnica",
      icon: <Settings className="w-5 h-5" />,
    },
    {
      id: "cond",
      label: "Foto da Condensadora",
      description: "Condensadora",
      icon: <Settings className="w-5 h-5" />,
    },
    {
      id: "comp_tec",
      label: "Foto da Etiqueta do Compressor",
      description: "Etiqueta do Compressor",
      icon: <Wrench className="w-5 h-5" />,
    },
    {
      id: "compressor",
      label: "Foto do Compressor",
      description: "Compressor",
      icon: <Wrench className="w-5 h-5" />,
    },
    {
      id: "temp_in",
      label: "Temperatura de Entrada",
      description: "Medição da temperatura de entrada",
      icon: <Wrench className="w-5 h-5" />,
      preventiveOnly: true,
    },
    {
      id: "temp_out",
      label: "Temperatura de Saída",
      description: "Medição da temperatura de saída",
      icon: <Wrench className="w-5 h-5" />,
      preventiveOnly: true,
    },
    {
      id: "press_high",
      label: "Pressão de Alta",
      description: "Medição da pressão de alta",
      icon: <Wrench className="w-5 h-5" />,
      preventiveOnly: true,
    },
    {
      id: "press_low",
      label: "Pressão de Baixa",
      description: "Medição da pressão de baixa",
      icon: <Wrench className="w-5 h-5" />,
      preventiveOnly: true,
    },
    {
      id: "temp_in",
      label: "Temperatura de Alta",
      description: "Medição da temperatura de alta",
      icon: <Wrench className="w-5 h-5" />,
      preventiveOnly: true,
    },
    {
      id: "temp_out",
      label: "Temperatura de Baixa",
      description: "Medição da temperatura de baixa",
      icon: <Wrench className="w-5 h-5" />,
      preventiveOnly: true,
    },
    {
      id: "amp",
      label: "Amperagem",
      description: "Medição da amperagem",
      icon: <Wrench className="w-5 h-5" />,
      preventiveOnly: true,
    },
  ],
  Self: [
    {
      id: "et_fan",
      label: "Etiqueta Técnica do Módulo Ventilador",
      description: "Etiqueta Técnica do Módulo Ventilador",
      icon: <Zap className="w-5 h-5" />,
    },
    {
      id: "fan",
      label: "Foto do Módulo Ventilador",
      description: "Foto do Módulo Ventilador",
      icon: <Zap className="w-5 h-5" />,
    },
    {
      id: "et_coil",
      label: "Etiqueta Técnica do Módulo Trocador",
      description: "Etiqueta Técnica do Módulo Trocador",
      icon: <Waves className="w-5 h-5" />,
    },
    {
      id: "coil",
      label: "Foto do Módulo Trocador",
      description: "Foto do Módulo Trocador",
      icon: <Waves className="w-5 h-5" />,
    },
    {
      id: "et_comp1",
      label: "Etiqueta Técnica do Compressor 1",
      description: "Etiqueta Técnica 1",
      icon: <Settings className="w-5 h-5" />,
    },
    {
      id: "et_comp2",
      label: "Etiqueta Técnica do Compressor 2",
      description: "Etiqueta Técnica 2",
      icon: <Zap className="w-5 h-5" />,
    },
    {
      id: "et_comp3",
      label: "Etiqueta Técnica do Compressor 3",
      description: "Etiqueta Técnica 3",
      icon: <Zap className="w-5 h-5" />,
    },
    {
      id: "comp1",
      label: "Foto do Compressor 1",
      description: "Foto do Compressor 1",
      icon: <Settings className="w-5 h-5" />,
    },
    {
      id: "comp2",
      label: "Foto do Compressor 2",
      description: "Foto do Compressor 2",
      icon: <Zap className="w-5 h-5" />,
    },
    {
      id: "comp3",
      label: "Foto do Compressor 3",
      description: "Foto do Compressor 3",
      icon: <Zap className="w-5 h-5" />,
    },
    {
      id: "et_cond",
      label: "Etiqueta do Módulo Condensador",
      description: "Etiqueta Técnica do Módulo Condensador",
      icon: <Zap className="w-5 h-5" />,
    },
    {
      id: "cond",
      label: "Foto do Módulo Condensador",
      description: "Foto do Módulo Condensador",
      icon: <Zap className="w-5 h-5" />,
    },
    {
      id: "air_flow",
      label: "Vazão de ar de saída no Módulo Ventilador",
      description: "Medição da vazão de ar de saída no Módulo Ventilador",
      icon: <Wrench className="w-5 h-5" />,
      preventiveOnly: true,
    },
    {
      id: "air_flow",
      label: "Foto do filtro de ar do Módulo Trocador",
      description: "Foto do filtro de ar",
      icon: <Wrench className="w-5 h-5" />,
      preventiveOnly: true,
    },
    {
      id: "air_flow",
      label: "Temperatura de Alta",
      description: "Medição da temperatura de alta",
      icon: <Wrench className="w-5 h-5" />,
      preventiveOnly: true,
    },
    {
      id: "air_flow",
      label: "Temperatura de Baixa",
      description: "Medição da temperatura de baixa",
      icon: <Wrench className="w-5 h-5" />,
      preventiveOnly: true,
    },
    {
      id: "air_flow",
      label: "Pressão de Alta",
      description: "Medição da pressão de alta",
      icon: <Wrench className="w-5 h-5" />,
      preventiveOnly: true,
    },
    {
      id: "air_flow",
      label: "Pressão de Baixa",
      description: "Medição da pressão de baixa",
      icon: <Wrench className="w-5 h-5" />,
      preventiveOnly: true,
    },
    {
      id: "air_flow",
      label: "Amperagem",
      description: "Medição da amperagem",
      icon: <Wrench className="w-5 h-5" />,
      preventiveOnly: true,
    },
    {
      id: "air_flow",
      label: "Módulo Trocador",
      description: "Módulo trocador",
      icon: <Wrench className="w-5 h-5" />,
      preventiveOnly: true,
    },
    {
      id: "air_flow",
      label: "Foto do Termostato",
      description: "Foto do Termostato",
      icon: <Wrench className="w-5 h-5" />,
      preventiveOnly: true,
    },
  ],
  Splitão: [
    {
      id: "fan",
      label: "Etiqueta Técnica do Módulo Ventilador",
      description: "Etiqueta Técnica do Módulo Ventilador",
      icon: <Zap className="w-5 h-5" />,
    },
    {
      id: "fan",
      label: "Foto do Módulo Ventilador",
      description: "Foto do Módulo Ventilador",
      icon: <Zap className="w-5 h-5" />,
    },
    {
      id: "coil",
      label: "Etiqueta Técnica do Módulo Trocador",
      description: "Etiqueta Técnica do Módulo Trocador",
      icon: <Waves className="w-5 h-5" />,
    },
    {
      id: "coil",
      label: "Foto do Módulo do Trocador",
      description: "Foto do Módulo do Trocador",
      icon: <Waves className="w-5 h-5" />,
    },
    {
      id: "comp3",
      label: "Etiqueta Técnica do Módulo Condensador",
      description: "Etiqueta Técnica do Módulo Condensador",
      icon: <Zap className="w-5 h-5" />,
    },
    {
      id: "comp3",
      label: "Foto do Módulo Condensador",
      description: "Foto do Módulo Condensador",
      icon: <Zap className="w-5 h-5" />,
    },
    {
      id: "comp1",
      label: "Etique Técnica do Compressor 1",
      description: "Etiqueta Técnica do Compressor 1",
      icon: <Settings className="w-5 h-5" />,
    },
    {
      id: "comp2",
      label: "Etique Técnica do Compressor 2",
      description: "Etiqueta Técnica do Compressor 2",
      icon: <Zap className="w-5 h-5" />,
    },
    {
      id: "comp3",
      label: "Etique Técnica do Compressor 3",
      description: "Etiqueta Técnica do Compressor 3",
      icon: <Zap className="w-5 h-5" />,
    },
    {
      id: "comp1",
      label: "Foto do Módulo Compressor 1",
      description: "Foto do Módulo Compressor 1",
      icon: <Settings className="w-5 h-5" />,
    },
    {
      id: "comp2",
      label: "Foto do Módulo Compressor 2",
      description: "Foto do Módulo Compressor 2",
      icon: <Zap className="w-5 h-5" />,
    },
    {
      id: "comp3",
      label: "Foto do Módulo Compressor 3",
      description: "Foto do Módulo Compressor 3",
      icon: <Zap className="w-5 h-5" />,
    },
    {
      id: "air_flow",
      label: "Vazão de ar de saída no Módulo Ventilador",
      description: "Medição da vazão de ar de saída no Módulo Ventilador",
      icon: <Wrench className="w-5 h-5" />,
      preventiveOnly: true,
    },
    {
      id: "air_flow",
      label: "Foto do filtro de ar do Módulo Trocador",
      description: "Foto do filtro de ar",
      icon: <Wrench className="w-5 h-5" />,
      preventiveOnly: true,
    },
    {
      id: "air_flow",
      label: "Temperatura de Alta",
      description: "Medição da temperatura de alta",
      icon: <Wrench className="w-5 h-5" />,
      preventiveOnly: true,
    },
    {
      id: "air_flow",
      label: "Temperatura de Baixa",
      description: "Medição da temperatura de baixa",
      icon: <Wrench className="w-5 h-5" />,
      preventiveOnly: true,
    },
    {
      id: "air_flow",
      label: "Pressão de Alta",
      description: "Medição da pressão de alta",
      icon: <Wrench className="w-5 h-5" />,
      preventiveOnly: true,
    },
    {
      id: "air_flow",
      label: "Pressão de Baixa",
      description: "Medição da pressão de baixa",
      icon: <Wrench className="w-5 h-5" />,
      preventiveOnly: true,
    },
    {
      id: "air_flow",
      label: "Amperagem",
      description: "Medição da amperagem",
      icon: <Wrench className="w-5 h-5" />,
      preventiveOnly: true,
    },
    {
      id: "air_flow",
      label: "Foto do Termostato",
      description: "Foto do Termostato",
      icon: <Wrench className="w-5 h-5" />,
      preventiveOnly: true,
    },
  ],
};
